### ISSUE TITLE
兄弟 这克隆下来运行直接报错。。

### ISSUE THREAD

**Issue by gujiwuqing** [wangtunan/vue-mooc#30]
Module '"../../../node_modules/vue/dist/vue"' has no exported member 'ref'.
    38 | </template>
    39 | <script lang="ts">
  > 40 | import { defineComponent, ref, onBeforeMount } from 'vue'
       |                           ^^^
    41 | import { getFooterLink } from '@/api/common'
    42 | import { FooterLinkConfig } from '@/types'
    43 | import { ERR_OK } from '@/api/config'

**Comment by wangtunan** [comment]
请升级typescript@4.3.5+即可
